Fix error

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -16,5 +16,20 @@ runs:
     - name: Get version
       id: get-version
       shell: bash
-      run: echo "version=$(cargo pkgid | cut -d "#" -f2)" >> $GITHUB_OUTPUT
+      # The output of `cargo pkgid` differs between different specs:
+      # See https://doc.rust-lang.org/cargo/commands/cargo-pkgid.html
+      #
+      # But always is true that, if contains '@', the version is the second part
+      # of a '@' split; and if not, the version is the second part of a '#' split.
+      run: |
+        id=$(cargo pkgid)
+        if [[ "$id" == *"@"* ]]; then
+          version=$(echo $id | cut -d '@' -f2)
+        else if [[ "$id" == *"#"* ]]; then
+          version=$(echo $id | cut -d '#' -f2)
+        else
+          echo "Error: Unable to determine version from cargo pkgid output: $id" >&2
+          exit 1
+        fi
+        echo "version=$version" >> $GITHUB_OUTPUT
       working-directory: ${{ inputs.working-directory }}
